package com.genealogy.platform.services.genealogy.visibility;

import com.genealogy.platform.services.genealogy.domain.Tree;
import com.genealogy.platform.services.genealogy.domain.UnlistedToken;
import com.genealogy.platform.services.genealogy.outbox.JdbcTreeOutboxWriter;
import com.genealogy.platform.services.genealogy.outbox.TreeEventPayloads;
import com.genealogy.platform.services.genealogy.persistence.TreeRepository;
import com.genealogy.platform.services.genealogy.persistence.UnlistedTokenRepository;

import java.security.SecureRandom;
import java.time.Duration;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * UNLISTED-visibility token service. Issues and revokes tokens
 * for trees in {@code UNLISTED} state. Mirrors
 * {@code contracts/genealogy/unlisted-token.yaml}:
 *
 * <ul>
 *   <li>Plaintext token is generated by {@link SecureRandom}, returned
 *       to the caller ONCE, never persisted.
 *   <li>Only the SHA-256 fingerprint is stored.
 *   <li>Per {@code design.md} §6.3 the HTTP layer MUST return
 *       {@code X-Robots-Tag: noindex} and {@code robots} meta
 *       equivalent for every UNLISTED page.
 *   <li>Per {@code design.md} §7.3 the event payload contains the
 *       fingerprint + opaque ids only; the plaintext token never
 *       leaves the issuance response.
 * </ul>
 */
public final class UnlistedTokenService {

    private static final Duration DEFAULT_LIFETIME = Duration.ofDays(7);
    private static final Duration MAX_LIFETIME = Duration.ofDays(30);

    private final TreeRepository treeRepository;
    private final UnlistedTokenRepository tokenRepository;
    private final JdbcTreeOutboxWriter outbox;
    private final SecureRandom random;

    public UnlistedTokenService(TreeRepository treeRepository,
                                UnlistedTokenRepository tokenRepository,
                                JdbcTreeOutboxWriter outbox) {
        this(treeRepository, tokenRepository, outbox, new SecureRandom());
    }

    public UnlistedTokenService(TreeRepository treeRepository,
                                UnlistedTokenRepository tokenRepository,
                                JdbcTreeOutboxWriter outbox,
                                SecureRandom random) {
        this.treeRepository = Objects.requireNonNull(treeRepository, "treeRepository");
        this.tokenRepository = Objects.requireNonNull(tokenRepository, "tokenRepository");
        this.outbox = Objects.requireNonNull(outbox, "outbox");
        this.random = Objects.requireNonNull(random, "random");
    }

    public IssuedToken issue(IssueCommand cmd) {
        Objects.requireNonNull(cmd, "cmd");
        Tree tree = treeRepository.findById(cmd.tenantId(), cmd.treeId())
                .orElseThrow(() -> new IllegalStateException("tree not found: " + cmd.treeId()));
        if (tree.visibility() != com.genealogy.platform.services.genealogy.domain.Visibility.UNLISTED) {
            throw new IllegalStateException(
                    "UNLISTED tokens require tree visibility = UNLISTED; current = "
                            + tree.visibility());
        }
        Instant now = cmd.now();
        Duration requested = cmd.lifetime() == null ? DEFAULT_LIFETIME : cmd.lifetime();
        if (requested.isZero() || requested.compareTo(MAX_LIFETIME) > 0) {
            throw new IllegalArgumentException(
                    "lifetime must be > 0 and <= " + MAX_LIFETIME);
        }
        UnlistedToken.GeneratedToken generated = UnlistedToken.generate(random);
        String tokenId = UUID.randomUUID().toString();
        UnlistedToken token = new UnlistedToken(
                tokenId,
                tree.treeId(),
                tree.tenantId(),
                generated.fingerprint(),
                cmd.scope(),
                cmd.branchId(),
                now,
                now.plus(requested),
                null,
                cmd.actorId(),
                null,
                null);
        tokenRepository.insert(token);
        outbox.enqueue(
                tree.treeId(),
                tree.tenantId(),
                TreeEventPayloads.EVENT_UNLISTED_TOKEN_ISSUED,
                TreeEventPayloads.UnlistedTokenIssuedEvent.fromToken(token),
                now,
                cmd.correlationId());
        return new IssuedToken(generated.plaintext(), token);
    }

    public UnlistedToken revoke(RevokeCommand cmd) {
        Objects.requireNonNull(cmd, "cmd");
        UnlistedToken existing = tokenRepository
                .findByFingerprint(cmd.tenantId(), cmd.fingerprint())
                .orElseThrow(() -> new IllegalStateException("token not found: " + cmd.fingerprint()));
        if (existing.revokedAt() != null) {
            return existing;
        }
        tokenRepository.revoke(
                cmd.tenantId(),
                cmd.fingerprint(),
                cmd.actorId(),
                cmd.reason(),
                cmd.now());
        UnlistedToken revoked = existing.revoked(cmd.actorId(), cmd.reason(), cmd.now());
        outbox.enqueue(
                revoked.treeId(),
                revoked.tenantId(),
                TreeEventPayloads.EVENT_UNLISTED_TOKEN_REVOKED,
                new TreeEventPayloads.UnlistedTokenRevokedEvent(
                        revoked.tokenId(),
                        revoked.treeId(),
                        revoked.fingerprint(),
                        cmd.actorId(),
                        cmd.reason(),
                        cmd.now()),
                cmd.now(),
                cmd.correlationId());
        return revoked;
    }

    /** Verify a candidate plaintext token against a tenant. Active = not revoked + not expired. */
    public UnlistedToken verify(String tenantId, String plaintext, Instant now) {
        Objects.requireNonNull(tenantId, "tenantId");
        Objects.requireNonNull(plaintext, "plaintext");
        Objects.requireNonNull(now, "now");
        String fingerprint = UnlistedToken.sha256HexLower(plaintext);
        UnlistedToken token = tokenRepository
                .findByFingerprint(tenantId, fingerprint)
                .orElseThrow(() -> new IllegalStateException("invalid token"));
        if (!token.isActive(now)) {
            throw new IllegalStateException("token expired or revoked");
        }
        return token;
    }

    public record IssueCommand(
            String tenantId,
            String treeId,
            UnlistedToken.Scope scope,
            String branchId,
            Duration lifetime,
            String actorId,
            String correlationId,
            Instant now) {
    }

    public record RevokeCommand(
            String tenantId,
            String fingerprint,
            String actorId,
            String reason,
            String correlationId,
            Instant now) {
    }

    public record IssuedToken(String plaintext, UnlistedToken persisted) {
        public IssuedToken {
            Objects.requireNonNull(plaintext, "plaintext");
            Objects.requireNonNull(persisted, "persisted");
        }
    }
}
