/**
 * apps/web/bench/report.mjs
 *
 * Markdown report emitter for the E5.1 tree renderer bench.
 * The report includes:
 *   - the policy summary (thresholds + closed sets);
 *   - a per-option results table (p50/p75/p95 layout+render,
 *     heap, payload, a11y, keyboard);
 *   - the per-budget pass/fail matrix;
 *   - a recommendation memo that synthesises the numbers +
 *     the ADR-E0.5-10 acceptance criteria into a single
 *     advisory note for the Web lead + Performance lead to
 *     close the ADR.
 *
 * The recommendation memo is **advisory only**; flipping
 * ADR-E0.5-10 from `DEFERRED` to `ACCEPTED` is owned by the
 * two leads per `architecture-decisions.md` line 554.
 */

/**
 * @param {{policy:any, size:string, personCount:number, repeats:number, options:Array<any>}} payload
 * @param {any} policy
 * @returns {string}
 */
export function renderMarkdown(payload, policy) {
  const lines = [];
  lines.push(`# Tree renderer benchmark report — ${payload.size}`);
  lines.push("");
  lines.push(`Generated by \`apps/web/bench/tree-renderer-bench.mjs\` for E5.1.`);
  lines.push("");
  lines.push("## Policy");
  lines.push("");
  lines.push(`- policyId: \`${payload.policy.policyId}\``);
  lines.push(`- interactionBudgetMs: ${policy.spec.interactionBudgetMs} (NFR2 p75)`);
  lines.push(`- memoryBudgetMb: ${policy.spec.memoryBudgetMb}`);
  lines.push(`- bundleBudgetKb: ${policy.spec.bundleBudgetKb}`);
  lines.push(`- hybridThresholdNodes: ${policy.spec.hybridThresholdNodes}`);
  lines.push(`- layoutWorkerEnabled: ${policy.spec.layoutWorkerEnabled}`);
  lines.push(`- neighborhoodOnlyRequired: ${policy.spec.neighborhoodOnlyRequired}`);
  lines.push(`- a11yAcceptableScore: ${policy.spec.a11yAcceptableScore}`);
  lines.push(`- keyboardAcceptableScore: ${policy.spec.keyboardAcceptableScore}`);
  lines.push(`- seedLocale: ${policy.spec.seedLocale}`);
  lines.push(`- auditClassOnBenchmark: ${policy.spec.auditClassOnBenchmark}`);
  lines.push("");
  lines.push(
    `Synthetic dataset: **${payload.size}** (${payload.personCount.toLocaleString()} persons).`,
  );
  lines.push(`Repeats per option: ${payload.repeats}.`);
  lines.push("");
  lines.push("## Results");
  lines.push("");
  lines.push(
    "| Option | p50 layout+render (ms) | p75 layout+render (ms) | p95 layout+render (ms) | peak heap (MB) | payload (kB) | a11y | keyboard | interaction ≤ budget | memory ≤ budget | bundle ≤ budget |",
  );
  lines.push("| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | :---: | :---: | :---: |");
  for (const o of payload.options) {
    const p75Total = o.p75LayoutMs + o.p75RenderMs;
    const p50Total = o.p50LayoutMs + o.p50RenderMs;
    const p95Total = o.p95LayoutMs + o.p95RenderMs;
    const payloadKb = (o.payloadBytes / 1024).toFixed(2);
    lines.push(
      `| ${o.option} | ${p50Total.toFixed(2)} | ${p75Total.toFixed(2)} | ${p95Total.toFixed(2)} | ${o.peakHeapMb.toFixed(2)} | ${payloadKb} | ${o.a11yScore.toFixed(2)} | ${o.keyboardScore.toFixed(2)} | ${o.meetsInteractionBudget ? "✅" : "❌"} | ${o.meetsMemoryBudget ? "✅" : "❌"} | ${o.meetsBundleBudget ? "✅" : "❌"} |`,
    );
  }
  lines.push("");
  lines.push("## Recommendation memo (advisory)");
  lines.push("");
  const recommendation = synthesiseRecommendation(payload, policy);
  lines.push(recommendation);
  lines.push("");
  lines.push("## Limitations");
  lines.push("");
  lines.push("- The harness runs in Node 22 + `node:worker_threads`; the");
  lines.push("  Worker boundary cost is measured but the JS engine JIT");
  lines.push("  profile is not Chromium-on-mid-tier-mobile. The");
  lines.push("  recommendation memo flags where the Node numbers are");
  lines.push("  likely conservative (SVG/Canvas layout is dominated by");
  lines.push("  string building; the real browser render loop is");
  lines.push("  faster).");
  lines.push("- The bench does not exercise ABAC redaction cost — the");
  lines.push("  redaction policy (E3.4) runs server-side and only the");
  lines.push("  redacted projection reaches the renderer. E5.3");
  lines.push("  re-measures when the projection API is wired.");
  lines.push("- The bundle-size proxy is the serialized renderer JS");
  lines.push("  output, not the webpack bundle; the real bundle is");
  lines.push("  measured by `apps/web/test/perf-budget.test.ts` after");
  lines.push("  `next build` once E5.3 lands.");
  lines.push("- Accessibility + keyboard scores are heuristics; the");
  lines.push("  authoritative audit is Playwright + axe-core in E5.5.");
  lines.push("");
  return lines.join("\n");
}

function synthesiseRecommendation(payload, policy) {
  const meetingInteraction = payload.options.filter((o) => o.meetsInteractionBudget);
  if (meetingInteraction.length === 0) {
    return [
      "**No option** meets the NFR2 p75 ≤ 2,5 s budget on the",
      `${payload.size} dataset in this Node-only harness. The`,
      "real browser run (Playwright in E5.3) is needed before",
      "the decision is finalised. Recommendation: **DEFER**",
      "ADR-E0.5-10 closure; raise the budget in NFR2 or shrink",
      "the viewport neighborhood before re-running.",
    ].join(" ");
  }
  const winner = meetingInteraction.sort((a, b) => {
    const aScore =
      a.p75LayoutMs + a.p75RenderMs + (1 - a.a11yScore) * 500 + (1 - a.keyboardScore) * 500;
    const bScore =
      b.p75LayoutMs + b.p75RenderMs + (1 - b.a11yScore) * 500 + (1 - b.keyboardScore) * 500;
    return aScore - bScore;
  })[0];
  const noteA11y =
    winner.a11yScore < policy.spec.a11yAcceptableScore
      ? `⚠️ accessibility score ${winner.a11yScore.toFixed(2)} is below the contract floor ${policy.spec.a11yAcceptableScore}; the chosen option requires a fallback semantic DOM before production rollout.`
      : `accessibility score ${winner.a11yScore.toFixed(2)} ≥ contract floor.`;
  const noteKeyboard =
    winner.keyboardScore < policy.spec.keyboardAcceptableScore
      ? `⚠️ keyboard score ${winner.keyboardScore.toFixed(2)} is below the contract floor ${policy.spec.keyboardAcceptableScore}; WAI-ARIA treeview pattern must be implemented before production rollout.`
      : `keyboard score ${winner.keyboardScore.toFixed(2)} ≥ contract floor.`;
  return [
    `**Advisory recommendation (NOT a decision):** option \`${winner.option}\``,
    `meets the NFR2 p75 ≤ ${policy.spec.interactionBudgetMs} ms budget on the ${payload.size} dataset`,
    `(${winner.p75LayoutMs + winner.p75RenderMs} ms). ${noteA11y} ${noteKeyboard}`,
    `The actual ADR-E0.5-10 closure remains owned by the Web lead + Performance lead per`,
    `\`architecture-decisions.md\` line 554. E5.1 closes the prototype benchmark; the closing`,
    `decision must wait for E5.3 (Playwright on-device profile) and E5.5 (axe-core audit).`,
  ].join(" ");
}
