// Regenerates `docs/ownership/team-map.yaml` from `config/teams.yaml`
// so CODEOWNERS, Renovate and Grafana OnCall all consume the same
// source of truth. Run via:
//
//   pnpm --filter @genealogy/codegen sync:teams
//
// E1.1 ships the script as a no-op until E1.6 wires Renovate.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..", "..");
const source = resolve(ROOT, "config/teams.yaml");
const target = resolve(ROOT, "docs/ownership/team-map.yaml");

interface TeamEntry {
  id: string;
  github: string;
  oncall: string;
}

function naiveParseTeams(yaml: string): TeamEntry[] {
  // E1.1 ships a regex-based parser; once E1.2 lands `yaml` will be a
  // proper devDependency. The regex is intentionally narrow and only
  // extracts the `teams:` subtree.
  const block = yaml.split("teams:")[1] ?? "";
  const re = /([a-z0-9-]+):\s*\n(?:[^\n]*\n)*?\s*github:\s*"([^"]+)"\s*\n(?:[^\n]*\n)*?\s*oncall:\s*([a-z0-9-]+)/g;
  const out: TeamEntry[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(block)) !== null) {
    out.push({ id: m[1]!, github: m[2]!, oncall: m[3]! });
  }
  return out;
}

const yaml = readFileSync(source, "utf8");
const teams = naiveParseTeams(yaml);
const now = new Date().toISOString();

const regenerated = [
  "# Mirror of config/teams.yaml for code-review tooling.",
  "# Regenerated by tools/scripts/sync-team-map.ts.",
  `version: 1`,
  `synced_at: ${now}`,
  `source: config/teams.yaml`,
  "teams:",
  ...teams.map((t) => `  - id: ${t.id}\n    github: "${t.github}"\n    oncall: ${t.oncall}`),
  "",
].join("\n");

writeFileSync(target, regenerated);
console.log(`[sync:teams] wrote ${teams.length} team entries to ${target}`);