/*
 * Shared cross-cutting library `platform-spring-boot-starter`.
 *
 * Spring Boot 3 auto-configuration that every Java service in the
 * Genealogy Platform monorepo depends on. The starter wires:
 *
 *   - OpenTelemetry tracing + metrics + OTLP exporter
 *     (`OpenTelemetryAutoConfiguration`).
 *   - OpenFeature SDK with a safe in-memory fallback so the service
 *     starts even when Flagsmith is unreachable
 *     (`OpenFeatureAutoConfiguration`).
 *   - Trusted tenant context propagation: Keycloak JWT extraction
 *     + RFC-9457 Problem Details + correlation-id MDC
 *     (`TrustedContextAutoConfiguration`).
 *   - jOOQ + Flyway datasource with tenant-aware connection
 *     routing (`JpaJooqFlywayAutoConfiguration`).
 *   - Audit hook (`AuditAutoConfiguration`) that publishes structured
 *     events to Micrometer for now (the dedicated audit-service
 *     is wired in E3.6).
 *   - Graceful shutdown + Kubernetes liveness/readiness probes
 *     (server config in `application.yml` template; this starter
 *     exposes the building blocks via
 *     `application/platform-spring-boot-defaults.yml`).
 *
 * The starter depends on the cross-cutting libs that the E1 family
 * has already approved (`platform-errors`, `platform-telemetry`,
 * `platform-security`, `platform-feature-flags`,
 * `platform-testing`) so each service only needs to depend on this
 * single starter to inherit the standard production wiring.
 */
plugins {
    `java-library`
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

dependencies {
    // Spring Boot base — we expose auto-configuration + web (BFF) + jOOQ
    api(libs.bundles.spring.runtime)
    api(libs.spring.boot.starter.grpc)
    api(libs.spring.boot.starter.actuator)

    // cross-cutting libs already in the monorepo
    api(project(":libs:platform-errors"))
    api(project(":libs:platform-telemetry"))
    api(project(":libs:platform-security"))
    api(project(":libs:platform-feature-flags"))

    // OTel Spring Boot starter (Micrometer bridge)
    api(libs.opentelemetry.spring.boot.starter)

    // OpenFeature SDK + Flagsmith provider (safe fallback is our own
    // `NoopOpenFeatureProvider` so the service still starts when the
    // Flagsmith backend is down).
    api(libs.openfeature.sdk)

    // Platform contracts — Apicurio / OpenFGA / Temporal / Keycloak
    // / S3 SDKs. These are `compileOnly` for E1.4 (E1.4 only ships
    // the wiring; the actual SDK usage lands in E4+). Declaring
    // them in the catalog keeps the version column authoritative.
    compileOnly(libs.apicurio.registry.client)
    compileOnly(libs.openfga.sdk)
    compileOnly(libs.temporal.sdk)
    compileOnly(libs.keycloak.admin.client)
    compileOnly(libs.aws.sdk.s3)

    // Spring's autoconfiguration contract — register our configs in
    // `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`
    // (file generated by this module's resources).

    // JSR-310 (java.time) Jackson support is already pulled in by
    // spring-boot-starter-web; we declare it explicitly so the lock
    // file is reproducible across services.
    api(libs.jackson.datatype.jsr310)

    testImplementation(libs.bundles.testing.unit)
    testImplementation(libs.bundles.testing.spring)
    testImplementation(libs.bundles.testing.testcontainers)
}

tasks.named<org.springframework.boot.gradle.tasks.bundling.BootJar>("bootJar") {
    enabled = false
}
