apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfga
  namespace: gp-data
  labels:
    app.kubernetes.io/part-of: genealogy-platform
    app.kubernetes.io/component: openfga
automountServiceAccountToken: false
